// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAISd6ke9iuqbsk5kxtPqtbr8q5raLDBFA',
    appId: '1:283319349126:web:b8197ddfb4fac459d2c607',
    messagingSenderId: '283319349126',
    projectId: 'clone-reddit-51ec2',
    authDomain: 'clone-reddit-51ec2.firebaseapp.com',
    storageBucket: 'clone-reddit-51ec2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIlTjmpxGFR9LWVtcDiR4StR1AZI_vhf0',
    appId: '1:283319349126:android:1bcf86f6de6f69a3d2c607',
    messagingSenderId: '283319349126',
    projectId: 'clone-reddit-51ec2',
    storageBucket: 'clone-reddit-51ec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArlQd3B4cWVki3MnFa5EliBgQ7Aqm7_pc',
    appId: '1:283319349126:ios:19962eefdeb6d218d2c607',
    messagingSenderId: '283319349126',
    projectId: 'clone-reddit-51ec2',
    storageBucket: 'clone-reddit-51ec2.appspot.com',
    iosBundleId: 'com.example.redditCloneFlutter',
  );
}
